FROM postgres:latest

VOLUME /var/lib/postgresql/data

EXPOSE 5432

# TO RUN:       docker run -d --name mono_postgres -p 5432:5432 --env-file .env postgres
# TO START:     docker start mono_postgres
# TO STOP:      docker stop mono_postgres